deps:
	@python3.10 -m pip install -r requirements.txt

run:
	@echo "not implemented yet"

test:
# 	@python3.10 -m pytest -v --cov=src --cov-report=term-missing
# 	@python3.10 -m pytest -v -k [FILTER]
	@python3.10 -m pytest -v

.PHONY: deps run test